# Generated by Django 4.0.4 on 2022-05-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
